<?php
/*
开发:kccpdt
开发GITHUB:kccpdt(https://github.com/kccpdt/)
本项目开发开源地址:https://github.com/kccpdt/kcc/
维护:kccpdt
维护GITHUB:kccpdt(https://github.com/kccpdt/)
本项目维护开源地址:https://github.com/kccpdt/kcc/
*/
error_reporting(E_ERROR|E_WARNING|E_PARSE);
date_default_timezone_set('Asia/Shanghai');
define('KCC_ROOT',str_replace('\\','/',realpath(dirname(dirname(__FILE__)).'/')).'/');
header("Content-type:text/html;charset=utf-8");
include_once(KCC_ROOT.'config/config.php');
include_once(KCC_ROOT.'function/function.php');
?>